services:
  nginx:
    container_name: kda_nginx
    image: nginx:latest
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - ./home:/usr/home

        # kda.com
        - ./kda.key:/etc/keys/priv.key
        - ./conf.d/nginx-kda.conf:/etc/nginx/conf.d/kda.conf
        - ../ca/leaf/certs/kda.com.cert.full.pem:/etc/nginx/ssl/public.pem
        - ../ca/leaf/certs/kda.com.cert.inter.pem:/etc/nginx/ssl/public.pem
        # - ../ca/leaf/certs/kda.com.cert.pem:/etc/nginx/ssl/public.pem
        - ../ca/leaf/private/kda.com.key.pem:/etc/nginx/ssl/privkey.pem

        # mTLS
        # - ../ca/leaf/ca/ca-bundle.pem:/etc/nginx/ssl/ca-bundle.pem
        # - ../ca/root/certs/ca.cert.pem:/etc/nginx/ssl/ca.pem
        # - ../ca/leaf/ca/ca-bundle.pem:/etc/nginx/ssl/ca.pem

        # example.com
        # - ./example.key:/etc/keys/priv.key
        # - ./conf.d/nginx-example.conf:/etc/nginx/conf.d/example.conf
        # - ../ca/leaf/certs/example.com.cert.full.pem:/etc/nginx/ssl/public.pem
        # - ../ca/leaf/private/example.com.key.pem:/etc/nginx/ssl/privkey.pem
